### ISSUE TITLE
Recipe isn't working

### ISSUE THREAD

**Issue by OctavesPlugins** [LousiesModPorts/SimpleCanisters#1]
Version: All versions
Error: The recipe for the heart amulet doesn't load
Log:

> `[30Dec2020 03:59:51.866] [Render thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe simplecanisters:heart_amulet
com.google.gson.JsonParseException: An ingredient entry needs either a tag or an item
	at net.minecraft.item.crafting.Ingredient.deserializeItemList(Ingredient.java:228) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:41) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:155) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.item.crafting.Ingredient.deserialize(Ingredient.java:189) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.item.crafting.ShapedRecipe.deserializeKey(ShapedRecipe.java:274) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.item.crafting.ShapedRecipe.access$000(ShapedRecipe.java:24) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.item.crafting.ShapedRecipe$Serializer.read(ShapedRecipe.java:298) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.item.crafting.ShapedRecipe$Serializer.read(ShapedRecipe.java:294) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.item.crafting.RecipeManager.deserializeRecipe(RecipeManager.java:144) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.item.crafting.RecipeManager.apply(RecipeManager.java:61) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.item.crafting.RecipeManager.apply(RecipeManager.java:38) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.resources.ReloadListener.lambda$reload$1(ReloadListener.java:14) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_252]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_252]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_252]
	at net.minecraft.resources.AsyncReloader.lambda$null$3(AsyncReloader.java:66) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:139) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.run(RecursiveEventLoop.java:22) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:109) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveUntil(ThreadTaskExecutor.java:122) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.reloadDatapacks(Minecraft.java:1905) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1758) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1728) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(WorldSelectionList.java:364) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(WorldSelectionList.java:273) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.mouseClicked(WorldSelectionList.java:228) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.gui.widget.list.AbstractList.mouseClicked(AbstractList.java:309) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.mouseClicked(INestedGuiEventHandler.java:31) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:92) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:427) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.MouseHelper.mouseButtonCallback(MouseHelper.java:90) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:185) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:86) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:184) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:112) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1025) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:612) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:52) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:105) [forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
[30Dec2020 03:59:51.874] [Render thread/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe simplecanisters:blue_heart_canister1
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'minecraft:crating_shapeless'
	at net.minecraft.item.crafting.RecipeManager.lambda$deserializeRecipe$9(RecipeManager.java:143) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_252]
	at net.minecraft.item.crafting.RecipeManager.deserializeRecipe(RecipeManager.java:142) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.item.crafting.RecipeManager.apply(RecipeManager.java:61) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.item.crafting.RecipeManager.apply(RecipeManager.java:38) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.resources.ReloadListener.lambda$reload$1(ReloadListener.java:14) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_252]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_252]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_252]
	at net.minecraft.resources.AsyncReloader.lambda$null$3(AsyncReloader.java:66) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:139) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.run(RecursiveEventLoop.java:22) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:109) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveUntil(ThreadTaskExecutor.java:122) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.reloadDatapacks(Minecraft.java:1905) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1758) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1728) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(WorldSelectionList.java:364) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(WorldSelectionList.java:273) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.mouseClicked(WorldSelectionList.java:228) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.gui.widget.list.AbstractList.mouseClicked(AbstractList.java:309) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.mouseClicked(INestedGuiEventHandler.java:31) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:92) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:427) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.MouseHelper.mouseButtonCallback(MouseHelper.java:90) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:185) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:86) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:184) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:112) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1025) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:612) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:52) ~[forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:105) [forge-1.16.4-35.1.10_mapped_snapshot_20201028-1.16.3-recomp.jar:?]`

**Comment by OctavesPlugins** [comment]
This is still an issue in the latest version, also the same with the apple!

**Comment by LousiesModPorts** [comment]
I hate JSON. I just uploaded a build which hopefully fixes it on the jenkins 👍
